//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictureSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot started.
        /// </summary>
        internal static string Program_Main_Bot_started_log {
            get {
                return ResourceManager.GetString("Program_Main_Bot_started_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot stopped.
        /// </summary>
        internal static string Program_Main_Bot_stopped_log {
            get {
                return ResourceManager.GetString("Program_Main_Bot_stopped_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Program_Main_Exit {
            get {
                return ResourceManager.GetString("Program_Main_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Program_Main_Hide {
            get {
                return ResourceManager.GetString("Program_Main_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Program_Main_Show {
            get {
                return ResourceManager.GetString("Program_Main_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessed activity.
        /// </summary>
        internal static string TelegramBot_AdminCommands_activity_accessed {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_activity_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string TelegramBot_AdminCommands_add_user_already_exists {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_add_user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to add user which already exists:.
        /// </summary>
        internal static string TelegramBot_AdminCommands_add_user_already_exists_log {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_add_user_already_exists_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully added.
        /// </summary>
        internal static string TelegramBot_AdminCommands_add_user_success {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_add_user_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succesfully added.
        /// </summary>
        internal static string TelegramBot_AdminCommands_add_user_success_log {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_add_user_success_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessed log.
        /// </summary>
        internal static string TelegramBot_AdminCommands_log_accessed {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_log_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enabled the partymode. YAY!.
        /// </summary>
        internal static string TelegramBot_AdminCommands_party {
            get {
                return ResourceManager.GetString("TelegramBot_AdminCommands_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error. Have you set a username?.
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_auth_no_username {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_auth_no_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error..
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_auth_not_successful {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_auth_not_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to authenticate, but entered wrong password..
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_auth_not_successful_log {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_auth_not_successful_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification successful..
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_auth_successful {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_auth_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has just authenticated a new telegram account.
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_auth_successful_log {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_auth_successful_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture not accepted. Please send as file..
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_deny_picture {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_deny_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to send a picture, but sent not as file..
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_deny_picture_log {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_deny_picture_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document incoming from.
        /// </summary>
        internal static string TelegramBot_Bot_OnMessage_document_incoming_log {
            get {
                return ResourceManager.GetString("TelegramBot_Bot_OnMessage_document_incoming_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. You have no Admin rights..
        /// </summary>
        internal static string TelegramBot_CommonCommands_admin_not_successful {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_admin_not_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to get admin, but entered wrong password.
        /// </summary>
        internal static string TelegramBot_CommonCommands_admin_not_successful_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_admin_not_successful_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now a Admin..
        /// </summary>
        internal static string TelegramBot_CommonCommands_admin_successful {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_admin_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has just authenticated as Admin.
        /// </summary>
        internal static string TelegramBot_CommonCommands_admin_successful_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_admin_successful_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression is disabled for the next picture..
        /// </summary>
        internal static string TelegramBot_CommonCommands_coff {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_coff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled compression.
        /// </summary>
        internal static string TelegramBot_CommonCommands_coff_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_coff_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string TelegramBot_CommonCommands_commands {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression is enabled..
        /// </summary>
        internal static string TelegramBot_CommonCommands_con {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled compression.
        /// </summary>
        internal static string TelegramBot_CommonCommands_con_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_con_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /amountactivity - Displays amount of pictures sent per user.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_activity_amount {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_activity_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /timeactivity - Displays date when users were last time active.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_activity_time {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_activity_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /add_user &lt;user&gt; - Adds a new user.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_add_user {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /admin &lt;pw&gt; - Authenticate as admin.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_admin {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /auth &lt;pw&gt; - Authenticates a new user.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_auth {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pwedit &lt;old&gt; &lt;new&gt; - Changes the password.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_change_pw {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_change_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /timeactivity_clear - Clears all stored activities.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_clear_activity {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_clear_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /amountactivity_clear - Clears amount counters.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_clear_amount {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_clear_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /coff - Disable comression for one picture.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_coff {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_coff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /con - enable compression.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_con {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help - Displays this text.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_help {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /log - Returns the last 100 lines of the log.
        /// </summary>
        internal static string TelegramBot_CommonCommands_help_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_help_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can´t parse command..
        /// </summary>
        internal static string TelegramBot_CommonCommands_nocommand {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_nocommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string TelegramBot_CommonCommands_Note_log {
            get {
                return ResourceManager.GetString("TelegramBot_CommonCommands_Note_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has no capture time (using servertime instead) from.
        /// </summary>
        internal static string TelegramBot_Date_taken_no_capturetime {
            get {
                return ResourceManager.GetString("TelegramBot_Date_taken_no_capturetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture accepted..
        /// </summary>
        internal static string TelegramBot_picture_accepted {
            get {
                return ResourceManager.GetString("TelegramBot_picture_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture accepted from.
        /// </summary>
        internal static string TelegramBot_picture_accepted_log {
            get {
                return ResourceManager.GetString("TelegramBot_picture_accepted_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted uncompressed picture..
        /// </summary>
        internal static string TelegramBot_picture_accepted_uncompressed {
            get {
                return ResourceManager.GetString("TelegramBot_picture_accepted_uncompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image compressing is active again..
        /// </summary>
        internal static string TelegramBot_picture_compression_autoenable {
            get {
                return ResourceManager.GetString("TelegramBot_picture_compression_autoenable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoenable compression for.
        /// </summary>
        internal static string TelegramBot_picture_compression_autoenable_log {
            get {
                return ResourceManager.GetString("TelegramBot_picture_compression_autoenable_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        internal static string TelegramBot_picture_saved_as_log {
            get {
                return ResourceManager.GetString("TelegramBot_picture_saved_as_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Wrong file type..
        /// </summary>
        internal static string TelegramBot_picture_wrong_filetype {
            get {
                return ResourceManager.GetString("TelegramBot_picture_wrong_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, wrong file type from.
        /// </summary>
        internal static string TelegramBot_picture_wrong_filetype_log {
            get {
                return ResourceManager.GetString("TelegramBot_picture_wrong_filetype_log", resourceCulture);
            }
        }
    }
}
